val sbtTypelevelVersion = "0.6.2"
addSbtPlugin("org.typelevel" % "sbt-typelevel" % sbtTypelevelVersion)
addSbtPlugin("org.typelevel" % "sbt-typelevel-scalafix" % sbtTypelevelVersion)
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % sbtTypelevelVersion)
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.14.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.5.1")
addSbtPlugin("com.armanbilge" % "sbt-bundlemon" % "0.1.4")
addSbtPlugin("io.spray"                    % "sbt-revolver"             % "0.10.0")
addSbtPlugin("ch.epfl.scala"               % "sbt-bloop"                % "1.5.11")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"             % "2.1.3")
addSbtPlugin("com.eed3si9n"                % "sbt-buildinfo"            % "0.11.0")
